export function seed() {
  const date = (offset, hour = 17) => {
    const d = new Date();
    d.setDate(d.getDate() + offset);
    d.setHours(hour, 0, 0, 0);
    return d.toISOString();
  };
  return {
    users: [
      { id: "parent", name: "Jordan Morgan", role: "parent", familyId: "f1" },
      {
        id: "player",
        name: "Alex Morgan",
        role: "player",
        familyId: "f1",
        playerId: "p1",
      },
      {
        id: "coach",
        name: "Taylor Brooks",
        role: "coach",
        teamIds: ["t1", "t2"],
      },
      { id: "staff", name: "Casey Rivera", role: "staff" },
      { id: "admin", name: "Sam Chen", role: "admin" },
    ],
    families: [
      {
        id: "f1",
        name: "Morgan family",
        email: "jordan@example.test",
        membership: "Active",
      },
      {
        id: "f2",
        name: "Wilson family",
        email: "avery@example.test",
        membership: "Active",
      },
    ],
    players: [
      {
        id: "p1",
        familyId: "f1",
        name: "Alex Morgan",
        age: 13,
        teamId: "t1",
        number: 12,
      },
      {
        id: "p2",
        familyId: "f1",
        name: "Riley Morgan",
        age: 10,
        teamId: "t2",
        number: 8,
      },
      {
        id: "p3",
        familyId: "f2",
        name: "Jamie Wilson",
        age: 13,
        teamId: "t1",
        number: 23,
      },
    ],
    teams: [
      { id: "t1", name: "U14 Falcons", coach: "Taylor Brooks" },
      { id: "t2", name: "U11 Sparks", coach: "Taylor Brooks" },
      { id: "t3", name: "U14 Wolves", coach: "Drew Ellis" },
      { id: "t4", name: "U14 Storm", coach: "Kai Reed" },
    ],
    programs: [
      {
        id: "a1",
        name: "Elite skills academy",
        type: "Skill Development",
        ages: "12–15",
        price: 240,
        capacity: 24,
        description:
          "Build confidence with purposeful ball handling, shooting, and footwork.",
        location: "Fieldhouse · Court 1",
        sessions: 8,
      },
      {
        id: "a2",
        name: "Fall youth league",
        type: "League",
        ages: "9–14",
        price: 180,
        capacity: 40,
        description:
          "A season of teamwork, competition, and finding your game.",
        location: "Community Centre",
        sessions: 10,
      },
      {
        id: "a3",
        name: "Weekend shooting lab",
        type: "Skill Development",
        ages: "10–16",
        price: 65,
        capacity: 12,
        description:
          "Dial in your shot with small-group coaching and personal feedback.",
        location: "Fieldhouse · Court 2",
        sessions: 2,
      },
    ],
    enrollments: [
      {
        id: "e1",
        playerId: "p1",
        programId: "a1",
        status: "Active",
        amount: 240,
      },
      {
        id: "e2",
        playerId: "p1",
        programId: "a2",
        status: "Active",
        amount: 180,
      },
      {
        id: "e3",
        playerId: "p2",
        programId: "a2",
        status: "Active",
        amount: 180,
      },
    ],
    events: [
      {
        id: "s1",
        title: "Skills academy",
        kind: "Training",
        start: date(0),
        minutes: 90,
        location: "Fieldhouse · Court 1",
        address: "Edmonton, Alberta",
        programId: "a1",
        teamId: "t1",
        playerIds: ["p1", "p3"],
      },
      {
        id: "s2",
        title: "Sparks team practice",
        kind: "Practice",
        start: date(1, 16),
        minutes: 60,
        location: "Community Centre",
        address: "Edmonton, Alberta",
        teamId: "t2",
        playerIds: ["p2"],
      },
      {
        id: "s3",
        title: "Falcons vs. Wolves",
        kind: "Game",
        start: date(2, 18),
        minutes: 90,
        location: "Fieldhouse · Court 1",
        address: "Edmonton, Alberta",
        teamId: "t1",
        opponentId: "t3",
        playerIds: ["p1", "p3"],
      },
      {
        id: "s4",
        title: "Shooting & footwork",
        kind: "Training",
        start: date(4),
        minutes: 60,
        location: "Fieldhouse · Court 2",
        address: "Edmonton, Alberta",
        programId: "a1",
        teamId: "t1",
        playerIds: ["p1", "p3"],
      },
    ],
    rsvps: [],
    attendance: [],
    products: [
      {
        id: "shirt",
        name: "The everyday tee",
        category: "ESSENTIALS",
        price: 30,
        color: "Forest",
        sizes: ["YS", "YM", "YL", "S", "M", "L", "XL"],
        stock: { YS: 12, YM: 12, YL: 12, S: 12, M: 12, L: 12, XL: 12 },
        creditEligible: true,
      },
      {
        id: "hoodie",
        name: "Courtside hoodie",
        category: "OFF-COURT",
        price: 65,
        color: "Oat",
        sizes: ["S", "M", "L", "XL"],
        stock: { S: 8, M: 8, L: 8, XL: 8 },
        creditEligible: false,
      },
      {
        id: "jersey",
        name: "Practice jersey",
        category: "ON-COURT",
        price: 45,
        color: "Clay",
        sizes: ["YS", "YM", "YL", "S", "M", "L"],
        stock: { YS: 10, YM: 10, YL: 10, S: 10, M: 10, L: 10 },
        creditEligible: false,
      },
    ],
    orders: [],
    credits: [],
    drills: [
      {
        id: "d1",
        name: "50-shot free throw challenge",
        category: "Shooting",
        minutes: 15,
        instructions:
          "Warm up, then shoot 5 sets of 10 free throws. Record your makes and attempts.",
      },
      {
        id: "d2",
        name: "Two-ball control",
        category: "Ball handling",
        minutes: 10,
        instructions:
          "Alternate low and high dribbles for 30 seconds, rest 30 seconds. Repeat 5 times.",
      },
      {
        id: "d3",
        name: "Athletic foundation",
        category: "Strength",
        minutes: 20,
        instructions:
          "Complete 3 rounds: 10 squats, 8 reverse lunges each side, 30-second plank. Focus on form.",
      },
    ],
    workouts: [
      {
        id: "w1",
        drillId: "d1",
        playerId: "p1",
        due: date(2),
        completed: false,
      },
      {
        id: "w2",
        drillId: "d2",
        playerId: "p1",
        due: date(3),
        completed: false,
      },
      {
        id: "w3",
        drillId: "d3",
        playerId: "p2",
        due: date(3),
        completed: false,
      },
    ],
    results: [],
    games: [
      {
        id: "g1",
        eventId: "s3",
        homeId: "t1",
        awayId: "t3",
        homeScore: 0,
        awayScore: 0,
        status: "Scheduled",
      },
      {
        id: "g2",
        homeId: "t3",
        awayId: "t4",
        homeScore: 48,
        awayScore: 42,
        status: "Final",
      },
    ],
    messages: [
      {
        id: "m1",
        channel: "t1",
        author: "Taylor Brooks",
        text: "Welcome to a new season! Bring a water bottle and your practice jersey. Excited to see everyone on court.",
        createdAt: date(-1, 10),
      },
      {
        id: "m2",
        channel: "t2",
        author: "Taylor Brooks",
        text: "Our next practice is at the Community Centre. Please update your RSVP before you arrive.",
        createdAt: date(-1, 11),
      },
    ],
    waivers: [],
    notices: [
      {
        id: "n1",
        title: "A new season starts here",
        text: "Fall programs are open. Find your next opportunity to grow.",
      },
    ],
  };
}
